FROM python:3.11-slim

WORKDIR /app

# зависимости для скрипта
RUN pip install --no-cache-dir psycopg2-binary pyotp

# чтобы был bash
RUN apt-get update && apt-get install -y --no-install-recommends bash \
  && rm -rf /var/lib/apt/lists/*
